spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: user-authentication-service
          uri: lb://USER-AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**
        - id: order-management-service
          uri: lb://ORDER-MANAGEMENT-SERVICE
          predicates:
            - Path= /order/**
          filters:
            - JwtAuthFilter
        - id: product-catalog-service
          uri: lb://PRODUCT-CATALOG-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - JwtAuthFilter
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8765