spring:
  application:
    name: USER-AUTHENTICATION-SERVICE
  zipkin:
    base-url: http://localhost:9411
management:
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId},%X{spanId}] %-5level %logger{36} - %msg%n"