spring:
  application:
    name: PRODUCT-CATALOG-SERVICE
  zipkin:
    base-url: http://localhost:9411/
management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId},%X{spanId}] %-5level %logger{36} - %msg%n"
